version: 0.2
env:
  variables:
    key: "value"

phases:
  install:
    commands:
      - python setup.py -q install
  build:
    commands:
      - echo "******** Building Jekyll site ********"
      
