version: 0.2
env:
  variables:
    key: "value"

phases:
  install:
    commands:
      - python setup.py -q install
  build:
    commands:
      - docker tag docker1:latest $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/docker1:latest
  post_build:
    commands:
      - echo Build completed
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/docker1
      - echo "******** Building docker site ********"
      
